# Generated by Django 2.1 on 2018-08-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': '发票数据', 'verbose_name_plural': '发票数据'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.FloatField(default=0.0, verbose_name='总计'),
        ),
    ]
