# Generated by Django 2.1 on 2018-08-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20180820_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='total',
            field=models.FloatField(default=0.0, verbose_name='商品单价'),
        ),
    ]
