# Generated by Django 2.1 on 2018-08-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_goods_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='total',
        ),
    ]
