# Generated by Django 2.1 on 2018-08-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_goods_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='商品单价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='商品总计'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='总计'),
        ),
    ]
