# Generated by Django 2.1 on 2018-08-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_auto_20180820_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='quant',
            field=models.IntegerField(default=1, verbose_name='商品数量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='商品小计'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='title',
            field=models.CharField(choices=[('办公用品', '办公用品'), ('出差报销', '出差报销')], max_length=100, verbose_name='发票类型'),
        ),
    ]
