# Generated by Django 2.1 on 2018-08-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0007_auto_20180821_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='remark',
            field=models.TextField(default='', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='title',
            field=models.CharField(choices=[('办公用品', '办公用品'), ('出差报销', '出差报销'), ('工资避税', '工资避税')], max_length=100, verbose_name='发票类型'),
        ),
    ]
