# Generated by Django 2.1 on 2018-08-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0008_auto_20180821_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
