# Generated by Django 2.1 on 2018-08-21 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0009_auto_20180821_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='部门名称')),
            ],
            options={
                'verbose_name': '公司部门',
                'verbose_name_plural': '公司部门',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.Department', verbose_name='公司部门'),
        ),
    ]
